# Generated by Django 4.2 on 2024-03-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bmart', '0003_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='OR '),
        ),
    ]
